Repository HYF-Class19/RCP-Team, pull requests merged in 2023-03, with the labels that each got.

#2 update readme
  .vscode/settings.json
  README.md
  public/assets/Agile.jpg
  public/assets/RCP-logo.jpg
  public/assets/roadmap.jpg
Labels: documentation

#3 01 coding approach v1
  codeApproach.md
Labels: documentation

#10 protoype 2 version 1
  prototype2.md
  public/assets/design/homepage-desktop-pro2-v1.png
  public/assets/design/homepage-mobile-pro2-v1.png
  public/assets/design/searchresult-desktop-pro2-v1.png
  public/assets/design/searchresult-mobile-pro2-v1.png
Labels: documentation, design

#11 proto-1
  README.md
  prototype1.md
  public/assets/design/prototype1-homepage.png
  public/assets/design/prototype1-mobile-homepage.png
Labels: documentation, design

#15 one recipe proto
  prototype1.md
  public/assets/design/one-recipe-proto-desktop.png
  public/assets/design/one-recipe-proto-mobile.png
Labels: documentation, design

#17 08 user persona 2
  README.md
  user-persona2.md
Labels: documentation

#16 07 user persona 1
  README.md
  user-persona1.md
Labels: documentation

#18 adding user persona2
  README.md
Labels: documentation

#20 add planning files
  .vscode/settings.json
  README.md
  planning/1-communication-plan.md
  planning/2-constraits.md
  planning/3-user-persona.md
  planning/4-backlog.md
  planning/5-prototype.md
  planning/6-design.md
  planning/7-development-strategy.md
  planning/8-retrospective.md
  planning/README.md
Labels: documentation

#22 10 planning
  .vscode/settings.json
  README.md
  planning/3-user-persona.md
  planning/4-backlog.md
  planning/5-prototype.md
  planning/6-design.md
  planning/8-retrospective.md
  planning/Assets/Agile.jpg
  planning/Assets/homepage-desktop-pro2-v1.png
  planning/Assets/homepage-mobile-pro2-v1.png
  planning/Assets/one-recipe-proto-desktop.png
  planning/Assets/one-recipe-proto-mobile.png
  planning/Assets/prototype1-homepage.png
  planning/Assets/prototype1-mobile-homepage.png
  planning/Assets/prototype1.md
  planning/Assets/prototype2.md
  planning/Assets/searchresult-desktop-pro2-v1.png
  planning/Assets/searchresult-mobile-pro2-v1.png
  prototype1.md
  prototype2.md
  user-persona1.md
  user-persona2.md
Labels: documentation

#23 09 project environment
  .eslintrc.json
  .gitignore
  .vscode/settings.json
  jsconfig.json
  next.config.js
  package-lock.json
  package.json
  src/app/api/hello/route.js
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
  src/app/page.module.css
Labels: development

#24 add development strategy
  .vscode/settings.json
  planning/7-development-strategy.md
Labels: documentation

#26 update the development strategy
  planning/7-development-strategy.md
Labels: documentation

#53 11 header v1
  package-lock.json
  package.json
  src/app/globals.css
  src/app/page.js
  src/app/page.module.css
Labels: development

#54 adding footer component
  package-lock.json
  package.json
  src/app/components/Footer.css
  src/app/components/Footer.js
  src/app/page.js
Labels: development

#57 adding figma homepage
  planning/5-prototype.md
  planning/6-design.md
  planning/Assets/figma-filterpage.png
  planning/Assets/figma-finaldesign.md
  planning/Assets/figma-homepage.png
  planning/Assets/figma-mobile-dropdown.png
  planning/Assets/figma-mobile-filterpage.png
  planning/Assets/figma-mobile-homepage.png
  planning/Assets/figma-mobile-popupfilter.png
  planning/Assets/figma-mobile.png
  planning/Assets/prototype-filterpage-final.png
  planning/Assets/prototype-homepage-final.png
  planning/Assets/prototype2-filterpage.png
  planning/Assets/prototype2-homepage.png
  planning/Assets/prototype2-mobile-filterpage.png
  planning/Assets/prototype2-mobile-homepage.png
  planning/Assets/prototype2.md
Labels: documentation, design

#59 36 maintenance
  src/app/components/Footer.css
  src/app/components/Footer.js
  src/app/components/Header.js
  src/app/components/NavBar.js
  src/app/components/slideShow.js
  src/app/page.js
Labels: maintenance

#60 13 recipes display v1
  package-lock.json
  package.json
  src/app/components/FilterComponent/Dietary.css
  src/app/components/FilterComponent/Dietary.js
  src/app/components/FilterComponent/ExcludeIngredients.css
  src/app/components/FilterComponent/ExcludeIngredients.js
  src/app/components/FilterComponent/Filter.css
  src/app/components/FilterComponent/Filter.js
  src/app/components/FilterComponent/IncludeIngredients.css
  src/app/components/FilterComponent/IncludeIngredients.js
  src/app/components/FilterComponent/MenuOrigin.css
  src/app/components/FilterComponent/MenuOrigin.js
  src/app/page.js
Labels: development

#61 fix commit on filter
  src/app/page.js
Labels: development

#62 add some change to style
  src/app/components/SlideShow.module.css
  src/app/components/slideShow.js
Labels: development

#67 37 firebase setup v2
  .gitignore
  README.md
  package-lock.json
  package.json
  src/app/services/.env.local
  src/app/services/Firebase.js
  src/app/services/Join.js
  src/app/services/Login.js
Labels: development

#68 fix mrcdn dsgn file, add about us, favorite, terms pages
  README.md
  planning/6-design.md
  planning/Assets/about-us.png
  planning/Assets/banner-orig.jpeg
  planning/Assets/banner2-orig.jpeg
  planning/Assets/favorite.png
  planning/Assets/one-recipe-figma.png
  planning/Assets/one-recipe.png
  planning/Assets/team-collage-desktop.png
  planning/Assets/team-collage-mobile.png
  planning/Assets/terms-of-use.png
Labels: documentation, design

#70 16 single v1
  package-lock.json
  package.json
  src/app/components/SingleRecipe.css
  src/app/components/SingleRecipe.js
  src/image/alarm.jpeg
  src/image/no-rating.jpeg
  src/image/people.jpeg
  src/image/rating.jpeg
Labels: development
