Repository HYF-Class19/RCP-Team, pull requests merged in 2023-04, with the labels that each got.

#73 single recipe
  src/app/components/SingleRecipe/SingleRecipe.css
  src/app/components/SingleRecipe/SingleRecipe.js
  src/app/components/SingleRecipe/page.css
  src/app/components/SingleRecipe/page.js
Labels: development

#74 14 filter v1
  src/app/components/FilterComponent/Dietary.js
  src/app/components/FilterComponent/ExcludeIngredients.js
  src/app/components/FilterComponent/Filter.js
  src/app/components/FilterComponent/IncludeIngredients.js
  src/app/components/FilterComponent/MenuOrigin.js
  src/app/components/FilterComponent/ShowRecipes.js
  src/app/components/SlideShow.js
  src/app/page.js
Labels: development

#76 single recipe
  src/app/components/SingleRecipe/SingleRecipe.js
Labels: development

#77 adding contact page and add recipe
  public/assets/pastries.jpg
  public/assets/veggie.jpg
  src/app/components/AddRecipe/AddRecipePage.css
  src/app/components/AddRecipe/AddRecipePage.js
  src/app/components/AddRecipe/RecipeBox.css
  src/app/components/AddRecipe/RecipeBox.js
  src/app/components/AddRecipe/RecipeForm.css
  src/app/components/AddRecipe/RecipeForm.js
  src/app/components/ContactPage/ContactBox.css
  src/app/components/ContactPage/ContactBox.js
  src/app/components/ContactPage/ContactForm.css
  src/app/components/ContactPage/ContactForm.js
  src/app/components/ContactPage/ContactPage.css
  src/app/components/ContactPage/ContactPage.js
Labels: development

#79 slide show styling
  src/app/components/SlideShow.js
  src/app/components/SlideShow.module.css
Labels: development

#78 about us page
  README.md
  package-lock.json
  package.json
  planning/Assets/team-collage-desktop.png
  planning/Assets/team-collage-mobile.png
  src/app/about/page.js
  src/app/components/Footer.js
  src/app/components/about/about.css
  src/app/components/about/about.js
  src/app/components/about/team.png
  src/app/components/about/teammob.png
Labels: development

#80 add a route to display a page with a random recipe
  src/app/components/NavBar.js
  src/app/components/RandomRecipe/SingleRecipe.css
  src/app/components/RandomRecipe/SingleRecipe.js
  src/app/components/RandomRecipe/page.css
  src/app/components/RandomRecipe/page.js
Labels: development

#82 fix navbar styling
  src/app/components/FilterComponent/Filter.css
  src/app/components/NavBar.css
Labels: development, fix bug

#83 single recipe home page link
  src/app/components/SingleRecipe/SingleRecipe.css
  src/app/components/SingleRecipe/SingleRecipe.js
Labels: development

#84 contact page
  package-lock.json
  package.json
  src/app/components/ContactPage/ContactBox.js
  src/app/components/ContactPage/ContactForm.css
  src/app/components/ContactPage/ContactForm.js
  src/app/components/ContactPage/ContactPage.css
  src/app/components/ContactPage/ContactPage.js
  src/app/components/Footer.js
  src/app/contact/page.js
Labels: development

#85 23 signup v2
  .env.local
  package-lock.json
  package.json
  src/app/account/Account.module.css
  src/app/account/Join.js
  src/app/account/Login.js
  src/app/account/page.js
  src/app/components/Header.js
  src/app/services/.env.local
  src/app/services/Firebase.js
  src/app/services/Join.js
  src/app/services/Login.js
Labels: development

#86 terms of use page
  src/app/components/Footer.js
  src/app/components/terms/bannerTerms.jpeg
  src/app/components/terms/terms.css
  src/app/components/terms/terms.js
  src/app/terms/page.js
Labels: development

#87 23 signup v2
  src/app/account/Join.js
  src/app/account/Login.js
  src/app/account/page.js
  src/app/components/AddRecipe/AddRecipePage.js
  src/app/components/AddRecipe/RecipeBox.js
  src/app/components/ContactPage/ContactBox.js
  src/app/components/ContactPage/ContactForm.js
  src/app/components/FilterComponent/Paginate.js
  src/app/components/FilterComponent/RecipeCard.js
  src/app/components/RandomRecipe/page.js
  src/app/components/SingleRecipe/page.js
  src/app/contact/page.js
  src/app/layout.js
  src/app/page.js
  src/app/terms/page.js
Labels: development

#88 fix terms and abus pages
  src/app/about/page.js
  src/app/components/ContactPage/ContactForm.js
  src/app/components/Footer.js
  src/app/components/terms/terms.js
  src/app/terms/page.js
Labels: development

#90 Add home button to navbar and logo
  src/app/components/FilterComponent/Filter.js
  src/app/components/FilterComponent/MenuOrigin.js
  src/app/components/FilterComponent/ShowRecipes.js
  src/app/components/Header.js
  src/app/components/NavBar.js
  src/app/components/RandomRecipe/SingleRecipe.css
  src/app/components/RandomRecipe/SingleRecipe.js
Labels: development

#91 footer and slide Show issue
  src/app/components/Footer.css
  src/app/components/SlideShow.js
  src/app/components/SlideShow.module.css
Labels: development

#94 back to home page issue
  src/app/components/SlideShow.js
  src/app/components/SlideShow.module.css
Labels: development

#96 28 wishlist v3
  src/app/components/Favorites/FavoriteRecipes.js
  src/app/components/Favorites/RecipeCard.js
  src/app/components/Favorites/page.css
  src/app/components/Favorites/page.js
  src/app/components/FilterComponent/RecipeCard.css
  src/app/components/FilterComponent/RecipeCard.js
  src/app/components/NavBar.css
  src/app/components/NavBar.js
  src/app/components/RandomRecipe/SingleRecipe.js
  src/app/components/SingleRecipe/SingleRecipe.css
  src/app/components/SingleRecipe/SingleRecipe.js
  src/app/services/Firebase.js
Labels: development

#98 store the rest of userinfo into firestore
  src/app/account/Join.js
Labels: development

#99 26 rating v3
  package-lock.json
  package.json
  src/app/components/SingleRecipe/ShowRating.css
  src/app/components/SingleRecipe/ShowRating.js
  src/app/components/SingleRecipe/SingleRecipe.js
Labels: development

#100 fix logo and design file
  planning/6-design.md
  public/assets/logo.png
Labels: documentation

#101 update add to favorites
  src/app/components/Favorites/RecipeCard.js
  src/app/components/SingleRecipe/ShowRating.js
  src/app/components/SingleRecipe/SingleRecipe.js
Labels: development

#102 26 rating v3
  package-lock.json
  package.json
  src/app/components/SingleRecipe/ShowRating.js
Labels: development

#103 fixing contact-form box
  src/app/contact/ContactForm.css
  src/app/contact/ContactForm.js
Labels: development

#104 28 wishlist v3
  src/app/components/Favorites/RecipeCard.js
  src/app/components/Favorites/page.css
  src/app/components/Favorites/page.js
  src/app/components/FilterComponent/RecipeCard.js
  src/app/components/FilterComponent/ShowRecipes.js
  src/app/components/RandomRecipe/SingleRecipe.js
  src/app/components/SingleRecipe/SingleRecipe.js
Labels: bug, development

#107 fix the navbar issue
  src/app/components/FilterComponent/page.js
Labels: development

#108 updating user ratingg
  src/app/components/SingleRecipe/SingleRecipe.js
  src/app/components/SingleRecipe/UpdateRating.js
Labels: development

#109 minor update
  README.md
  package-lock.json
  package.json
Labels: bug

#111 move the api header to api file
  src/app/api/hello/route.js
  src/app/components/FilterComponent/ShowRecipes.js
  src/app/components/RandomRecipe/SingleRecipe.js
  src/app/components/SingleRecipe/SingleRecipe.js
  src/app/components/SlideShow.js
  src/app/services/Firebase.js
  src/app/services/Spoonacular.js
Labels: development

#114 fix account responsive design
  public/assets/Rectangle-account.png
  src/app/account/Account.module.css
  src/app/account/Join.js
  src/app/account/Login.js
  src/app/account/page.js
Labels: design

#115 fix slider responsive
  src/app/components/SlideShow.js
  src/app/components/SlideShow.module.css
Labels: design

#116 adapt about
  src/app/components/about/about.css
Labels: development

#117 adapt terms
  src/app/components/terms/terms.css
Labels: development

#118 26 rating v3
  src/app/components/SingleRecipe/SingleRecipe.css
  src/app/components/SlideShow.js
Labels: development

#119 fix the random issue
  src/app/components/RandomRecipe/SingleRecipe.js
  src/app/components/RandomRecipe/page.js
Labels: development

#121 fix header responsive
  src/app/components/Header.css
  src/app/components/Header.js
Labels: design

#120 Fix recipe image
  src/app/components/FilterComponent/MenuOrigin.js
  src/app/components/FilterComponent/ShowRecipes.js
Labels: bug, development

#122 fix recipe responsive fast fix
  src/app/components/FilterComponent/Filter.css
  src/app/components/FilterComponent/ShowRecipes.css
  src/app/page.css
  src/app/page.js
Labels: design

#124 fix navbar toggle
  src/app/components/NavBar.js
Labels: bug

#125 fix show-recipes component
  src/app/components/Favorites/page.js
  src/app/components/FilterComponent/Filter.js
  src/app/components/FilterComponent/Paginate.css
  src/app/components/FilterComponent/Paginate.js
  src/app/components/FilterComponent/ShowRecipes.css
  src/app/components/FilterComponent/ShowRecipes.js
  src/app/components/FilterComponent/page.js
  src/app/components/Header.js
  src/app/components/RandomRecipe/page.js
  src/app/components/SingleRecipe/SingleRecipe.js
  src/app/components/SlideShow.module.css
  src/app/components/terms/terms.css
  src/app/page.js
Labels: bug

#128 improving contact page and footer
  src/app/components/Footer.css
  src/app/contact/ContactBox.css
  src/app/contact/ContactForm.css
Labels: development, fix bug

#130 add styling to favorites
  src/app/components/Favorites/RecipeCard.css
  src/app/components/Favorites/RecipeCard.js
  src/app/components/Favorites/page.css
  src/app/components/Favorites/page.js
Labels: bug

#129 adapt for 11 inch
  src/app/page.css
  src/app/page.js
Labels: design, development

#131 fix the slider mobile version issue
  src/app/components/SingleRecipe/SingleRecipe.css
  src/app/components/SingleRecipe/SingleRecipe.js
  src/app/components/SlideShow.js
  src/app/components/SlideShow.module.css
Labels: development

#132 change for to htmlFor
  src/app/components/FilterComponent/MenuOrigin.js
Labels: bug

#133 26 rating v3
  package-lock.json
  package.json
  src/app/components/SingleRecipe/SingleRecipe.css
  src/app/components/SingleRecipe/SingleRecipe.js
  src/app/components/SingleRecipe/UpdateRating.js
  src/app/components/SlideShow.js
  src/app/components/SlideShow.module.css
Labels: development

#134 firebase call fix
  src/app/components/SingleRecipe/ShowRating.js
  src/app/components/SingleRecipe/SingleRecipe.js
  src/app/components/SingleRecipe/UpdateRating.js
Labels: development

#135 firebase call fix
  src/app/components/SingleRecipe/ShowRating.js
  src/app/components/SingleRecipe/UpdateRating.js
Labels: development

#136 store info in local storage & redirect to favorite
  src/app/account/Login.js
Labels: development

#137 add signout to the header
  README.md
  package-lock.json
  package.json
  src/app/account/Login.js
  src/app/components/Header.js
Labels: development

#138 store the user info when join also and login him
  src/app/account/Join.js
  src/app/account/Login.js
Labels: development

#139 prevent access to favorite without auth
  public/assets/alarm.jpeg
  public/assets/people.jpeg
  src/app/account/Join.js
  src/app/components/Favorites/RecipeCard.js
  src/app/components/FilterComponent/RecipeCard.js
  src/app/components/FilterComponent/ShowRecipes.js
  src/app/components/SingleRecipe/SingleRecipe.js
  src/app/contact/ContactForm.js
Labels: bug
